In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from pathlib import Path

BASE_DIR = Path("/content/drive/MyDrive/Revi_Diploma_Reproducibility_Package")
DATA_DIR = BASE_DIR / "02_Data"
RESULTS_DIR = BASE_DIR / "04_Results"
TESTS_DIR = BASE_DIR / "05_Statistical_Tests"

DATA_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
TESTS_DIR.mkdir(parents=True, exist_ok=True)

FULL_DATASET_PATH = DATA_DIR / "crypto_dataset_full.csv"

print("Base folder:", BASE_DIR)
print("Dataset path:", FULL_DATASET_PATH)
print("Results folder:", RESULTS_DIR)

Base folder: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package
Dataset path: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/02_Data/crypto_dataset_full.csv
Results folder: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results

In [9]:
import pandas as pd

df = pd.read_csv(FULL_DATASET_PATH)

# Sigurohemi që kolona date ekziston
if "date" not in df.columns:
    raise ValueError("Dataset-i nuk ka kolonën 'date'.")

df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date").reset_index(drop=True)

print("Dataset shape:", df.shape)
print("Start date:", df["date"].min().date())
print("End date:", df["date"].max().date())
print("Missing values total:", df.isna().sum().sum())
print("Duplicate dates:", df["date"].duplicated().sum())
print("Number of columns:", len(df.columns))

print("\nFirst rows:")
display(df.head())

print("\nLast rows:")
display(df.tail())

Dataset shape: (2141, 51)
Start date: 2019-02-20
End date: 2024-12-30
Missing values total: 0
Duplicate dates: 0
Number of columns: 51

First rows:

,date,BTC_open,BTC_high,BTC_low,BTC_close,BTC_volume,ETH_open,ETH_high,ETH_low,ETH_close,...,BNB_return1d,BNB_vol7d,corr_BTC_ETH_30d,corr_BTC_BNB_30d,corr_ETH_BNB_30d,fear_greed,day_of_week,month,quarter,is_weekend
0,2019-02-20,3946.685059,4000.486328,3926.246826,3999.820557,8693373948,145.172729,149.554337,142.502121,149.554337,...,0.038150,0.041167,0.977413,0.773581,0.805449,50.0,2,2,1,0
1,2019-02-21,4000.256836,4010.009521,3940.108154,3954.118164,7775128102,149.352325,149.352325,144.563812,146.130844,...,-0.043148,0.046830,0.980774,0.811031,0.839918,50.0,3,2,1,0
2,2019-02-22,3952.406494,4006.538330,3950.816406,4005.526611,7826525254,146.073257,149.268616,145.206543,149.092453,...,0.032805,0.045201,0.983417,0.841434,0.868393,50.0,4,2,1,0
3,2019-02-23,3998.916260,4166.286133,3968.726807,4142.526855,8922258316,148.676620,159.125870,147.331055,158.795425,...,-0.005104,0.043849,0.986384,0.859361,0.884834,50.0,5,2,1,1
4,2019-02-24,4145.458008,4210.641602,3793.708984,3810.427490,10794227451,158.902405,165.549622,135.852661,135.852661,...,-0.062022,0.054951,0.986825,0.871477,0.894240,50.0,6,2,1,1

Last rows:

,date,BTC_open,BTC_high,BTC_low,BTC_close,BTC_volume,ETH_open,ETH_high,ETH_low,ETH_close,...,BNB_return1d,BNB_vol7d,corr_BTC_ETH_30d,corr_BTC_BNB_30d,corr_ETH_BNB_30d,fear_greed,day_of_week,month,quarter,is_weekend
2136,2024-12-26,99297.695312,99884.570312,95137.882812,95795.515625,47054980873,3493.304199,3512.604492,3302.306396,3331.225830,...,-0.019887,0.032228,0.695231,0.590542,0.670392,79.0,3,12,4,0
2137,2024-12-27,95704.976562,97294.843750,93310.742188,94164.859375,52419934565,3331.053711,3436.710693,3302.575684,3328.916992,...,0.003006,0.031773,0.724529,0.560711,0.672278,74.0,4,12,4,0
2138,2024-12-28,94160.187500,95525.898438,94014.289062,95163.929688,24107436185,3328.774658,3419.920166,3318.033936,3397.902344,...,0.044218,0.032954,0.736994,0.493552,0.621153,72.0,5,12,4,1
2139,2024-12-29,95174.054688,95174.875000,92881.789062,93530.226562,29635885267,3397.862549,3406.648438,3321.664795,3349.513428,...,-0.037734,0.036086,0.753902,0.483281,0.618036,73.0,6,12,4,1
2140,2024-12-30,93527.195312,94903.320312,91317.132812,92643.210938,56188003691,3349.585938,3428.527344,3298.804443,3356.392578,...,0.014979,0.025997,0.777112,0.441210,0.634887,65.0,0,12,4,0

In [10]:
required_columns = [
    "date",
    "BTC_open", "BTC_high", "BTC_low", "BTC_close", "BTC_volume",
    "ETH_open", "ETH_high", "ETH_low", "ETH_close", "ETH_volume",
    "BNB_open", "BNB_high", "BNB_low", "BNB_close", "BNB_volume",
    "BTC_RSI14", "BTC_EMA7", "BTC_EMA21", "BTC_EMA50", "BTC_MACD", "BTC_MACD_signal", "BTC_BB_width",
    "ETH_RSI14", "ETH_EMA7", "ETH_EMA21", "ETH_EMA50", "ETH_MACD", "ETH_MACD_signal", "ETH_BB_width",
    "BNB_RSI14", "BNB_EMA7", "BNB_EMA21", "BNB_EMA50", "BNB_MACD", "BNB_MACD_signal", "BNB_BB_width",
    "BTC_return1d", "ETH_return1d", "BNB_return1d",
    "BTC_vol7d", "ETH_vol7d", "BNB_vol7d",
    "corr_BTC_ETH_30d", "corr_BTC_BNB_30d", "corr_ETH_BNB_30d",
    "fear_greed",
    "day_of_week", "month", "quarter", "is_weekend"
]

missing_required = [col for col in required_columns if col not in df.columns]

if missing_required:
    print("Missing required columns:")
    print(missing_required)
else:
    print("All required columns are present.")

All required columns are present.

In [12]:
TRAIN_END = pd.Timestamp('2022-12-31')
VAL_END = pd.Timestamp('2023-06-30')

train_df = df[df["date"] <= TRAIN_END].copy()
val_df = df[(df["date"] > TRAIN_END) & (df["date"] <= VAL_END)].copy()
test_df = df[df["date"] > VAL_END].copy()

summary = pd.DataFrame([
    {
        "split": "Train",
        "start_date": train_df["date"].min().date(),
        "end_date": train_df["date"].max().date(),
        "rows": len(train_df),
        "columns": train_df.shape[1]
    },
    {
        "split": "Validation",
        "start_date": val_df["date"].min().date(),
        "end_date": val_df["date"].max().date(),
        "rows": len(val_df),
        "columns": val_df.shape[1]
    },
    {
        "split": "Test",
        "start_date": test_df["date"].min().date(),
        "end_date": test_df["date"].max().date(),
        "rows": len(test_df),
        "columns": test_df.shape[1]
    }
])

display(summary)

train_df.to_csv(DATA_DIR / "crypto_train_2019_2022.csv", index=False)
val_df.to_csv(DATA_DIR / "crypto_validation_2023_H1.csv", index=False)
test_df.to_csv(DATA_DIR / "crypto_test_2023_H2_2024.csv", index=False)
summary.to_csv(DATA_DIR / "dataset_split_summary.csv", index=False)

print("Split files saved in:", DATA_DIR)

        split  start_date    end_date  rows  columns
0       Train  2019-02-20  2022-12-31  1411       51
1  Validation  2023-01-01  2023-06-30   181       51
2        Test  2023-07-01  2024-12-30   549       51

Split files saved in: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/02_Data

In [13]:
assert train_df["date"].max() < val_df["date"].min(), "Train overlaps with Validation."
assert val_df["date"].max() < test_df["date"].min(), "Validation overlaps with Test."

print("Anti-leakage chronological split check: PASSED")
print("Train ends at:", train_df["date"].max().date())
print("Validation starts at:", val_df["date"].min().date())
print("Validation ends at:", val_df["date"].max().date())
print("Test starts at:", test_df["date"].min().date())

Anti-leakage chronological split check: PASSED
Train ends at: 2022-12-31
Validation starts at: 2023-01-01
Validation ends at: 2023-06-30
Test starts at: 2023-07-01

In [14]:
dataset_report = {
    "total_rows": len(df),
    "total_columns": df.shape[1],
    "start_date": str(df["date"].min().date()),
    "end_date": str(df["date"].max().date()),
    "missing_values": int(df.isna().sum().sum()),
    "duplicate_dates": int(df["date"].duplicated().sum()),
    "train_rows": len(train_df),
    "validation_rows": len(val_df),
    "test_rows": len(test_df),
    "train_period": f"{train_df['date'].min().date()} to {train_df['date'].max().date()}",
    "validation_period": f"{val_df['date'].min().date()} to {val_df['date'].max().date()}",
    "test_period": f"{test_df['date'].min().date()} to {test_df['date'].max().date()}",
}

report_df = pd.DataFrame([dataset_report])
display(report_df)

report_df.to_csv(DATA_DIR / "dataset_quality_report.csv", index=False)
print("Dataset quality report saved.")

,total_rows,total_columns,start_date,end_date,missing_values,duplicate_dates,train_rows,validation_rows,test_rows,train_period,validation_period,test_period
0,2141,51,2019-02-20,2024-12-30,0,0,1411,181,549,2019-02-20 to 2022-12-31,2023-01-01 to 2023-06-30,2023-07-01 to 2024-12-30

Dataset quality report saved.

In [15]:
!pip -q install statsmodels scikit-learn tqdm

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
from pathlib import Path
from tqdm.auto import tqdm

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("ARIMA setup completed.")

ARIMA setup completed.

In [16]:
ASSETS = {
    "BTC": "BTC_close",
    "ETH": "ETH_close",
    "BNB": "BNB_close"
}

HORIZONS = [1, 7, 30]

def compute_forecast_metrics(y_true, y_pred, origin_price):
    """
    Metrics:
    - MAE, RMSE, MAPE, R2
    - Directional Accuracy matet kundrejt origin_price:
      nëse modeli parashikon drejtimin e saktë nga origin deri te target.
    """
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    origin_price = np.asarray(origin_price, dtype=float)

    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = np.mean(np.abs((y_true - y_pred) / np.clip(np.abs(y_true), 1e-8, None))) * 100
    r2 = r2_score(y_true, y_pred)

    true_direction = np.sign(y_true - origin_price)
    pred_direction = np.sign(y_pred - origin_price)
    directional_accuracy = np.mean(true_direction == pred_direction) * 100

    return {
        "MAE": round(float(mae), 2),
        "RMSE": round(float(rmse), 2),
        "MAPE": round(float(mape), 2),
        "R2": round(float(r2), 4),
        "Directional_Accuracy": round(float(directional_accuracy), 2)
    }

print("Metrics function ready.")

Metrics function ready.

In [17]:
def select_arima_order_by_aic(train_series, max_p=5, max_q=3, d_values=[1]):
    """
    Zgjedh ARIMA(p,d,q) sipas AIC vetëm mbi Train.
    """
    best_order = None
    best_aic = np.inf
    results = []

    for p in range(max_p + 1):
        for d in d_values:
            for q in range(max_q + 1):
                order = (p, d, q)
                try:
                    model = ARIMA(
                        train_series,
                        order=order,
                        enforce_stationarity=False,
                        enforce_invertibility=False
                    )
                    fitted = model.fit()
                    aic = fitted.aic

                    results.append({
                        "order": order,
                        "aic": aic
                    })

                    if aic < best_aic:
                        best_aic = aic
                        best_order = order

                except Exception:
                    continue

    if best_order is None:
        raise ValueError("No valid ARIMA order found.")

    return best_order, best_aic, pd.DataFrame(results)


arima_orders = []
arima_order_details = []

for asset, target_col in ASSETS.items():
    print(f"\nSelecting ARIMA order for {asset}...")

    train_series = train_df.set_index("date")[target_col].astype(float)

    best_order, best_aic, details = select_arima_order_by_aic(
        train_series=train_series,
        max_p=5,
        max_q=3,
        d_values=[1]
    )

    print(f"{asset} best order: {best_order}, AIC: {best_aic:.2f}")

    arima_orders.append({
        "asset": asset,
        "target_col": target_col,
        "best_order": str(best_order),
        "best_aic": round(float(best_aic), 2)
    })

    details["asset"] = asset
    arima_order_details.append(details)

arima_orders_df = pd.DataFrame(arima_orders)
arima_order_details_df = pd.concat(arima_order_details, ignore_index=True)

display(arima_orders_df)

arima_orders_df.to_csv(RESULTS_DIR / "arima_orders.csv", index=False)
arima_order_details_df.to_csv(RESULTS_DIR / "arima_order_search_details.csv", index=False)

print("ARIMA order files saved.")

Selecting ARIMA order for BTC...

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

BTC best order: (5, 1, 0), AIC: 23753.24

Selecting ARIMA order for ETH...

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

ETH best order: (5, 1, 3), AIC: 16590.69

Selecting ARIMA order for BNB...

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

BNB best order: (5, 1, 1), AIC: 11438.84

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

  asset target_col best_order  best_aic
0   BTC  BTC_close  (5, 1, 0)  23753.24
1   ETH  ETH_close  (5, 1, 3)  16590.69
2   BNB  BNB_close  (5, 1, 1)  11438.84

ARIMA order files saved.

In [18]:
def arima_walk_forward_forecast(train_val_series, test_series, order, horizon):
    """
    Walk-forward forecasting:
    - Modeli trajnohet fillimisht mbi Train + Validation.
    - Për çdo hap në Test, bëhet forecast për horizon ditë përpara.
    - Pas çdo hapi, modeli përditësohet me vlerën reale të re të Test,
      por pa përdorur target-in e ardhshëm.
    """
    train_val_series = train_val_series.astype(float)
    test_series = test_series.astype(float)

    fitted = ARIMA(
        train_val_series,
        order=order,
        enforce_stationarity=False,
        enforce_invertibility=False
    ).fit()

    records = []

    for i in range(0, len(test_series) - horizon + 1):
        forecast = fitted.forecast(steps=horizon)
        predicted_value = float(forecast.iloc[-1])

        if i == 0:
            origin_date = train_val_series.index[-1]
            origin_price = float(train_val_series.iloc[-1])
        else:
            origin_date = test_series.index[i - 1]
            origin_price = float(test_series.iloc[i - 1])

        target_date = test_series.index[i + horizon - 1]
        actual_value = float(test_series.iloc[i + horizon - 1])

        records.append({
            "date": target_date,
            "origin_date": origin_date,
            "asset": None,
            "horizon": horizon,
            "actual": actual_value,
            "origin_price": origin_price,
            "arima_pred": predicted_value
        })

        # Përditëso modelin me observimin real të sapo kaluar
        if i < len(test_series) - horizon:
            new_observation = test_series.iloc[[i]]
            try:
                fitted = fitted.append(new_observation, refit=False)
            except Exception:
                updated_history = pd.concat([train_val_series, test_series.iloc[:i+1]])
                fitted = ARIMA(
                    updated_history,
                    order=order,
                    enforce_stationarity=False,
                    enforce_invertibility=False
                ).fit()

    return pd.DataFrame(records)


train_indexed = train_df.set_index("date")
val_indexed = val_df.set_index("date")
test_indexed = test_df.set_index("date")

arima_predictions_all = []
arima_metrics_all = []

for _, row in arima_orders_df.iterrows():
    asset = row["asset"]
    target_col = row["target_col"]
    order = eval(row["best_order"])

    print(f"\nRunning ARIMA forecasts for {asset}, order={order}")

    train_val_series = pd.concat([
        train_indexed[target_col],
        val_indexed[target_col]
    ])

    test_series = test_indexed[target_col]

    for horizon in HORIZONS:
        print(f"  Horizon H={horizon}")

        pred_df = arima_walk_forward_forecast(
            train_val_series=train_val_series,
            test_series=test_series,
            order=order,
            horizon=horizon
        )

        pred_df["asset"] = asset
        pred_df["model"] = "ARIMA"

        metrics = compute_forecast_metrics(
            y_true=pred_df["actual"],
            y_pred=pred_df["arima_pred"],
            origin_price=pred_df["origin_price"]
        )

        metrics_row = {
            "model": "ARIMA",
            "asset": asset,
            "horizon": horizon,
            "n_predictions": len(pred_df),
            **metrics
        }

        arima_predictions_all.append(pred_df)
        arima_metrics_all.append(metrics_row)

arima_predictions_df = pd.concat(arima_predictions_all, ignore_index=True)
arima_metrics_df = pd.DataFrame(arima_metrics_all)

display(arima_metrics_df)

arima_predictions_df.to_csv(RESULTS_DIR / "arima_predictions.csv", index=False)
arima_metrics_df.to_csv(RESULTS_DIR / "arima_metrics.csv", index=False)

print("ARIMA predictions and metrics saved.")
print("Predictions:", RESULTS_DIR / "arima_predictions.csv")
print("Metrics:", RESULTS_DIR / "arima_metrics.csv")

Running ARIMA forecasts for BTC, order=(5, 1, 0)
  Horizon H=1

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

  Horizon H=7

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

  Horizon H=30

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

Running ARIMA forecasts for ETH, order=(5, 1, 3)
  Horizon H=1

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

  Horizon H=7

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

  Horizon H=30

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Running ARIMA forecasts for BNB, order=(5, 1, 1)
  Horizon H=1

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

  Horizon H=7

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

  Horizon H=30

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

,model,asset,horizon,n_predictions,MAE,RMSE,MAPE,R2,Directional_Accuracy
0,ARIMA,BTC,1,549,1029.50,1567.23,1.77,0.9940,48.63
1,ARIMA,BTC,7,543,2845.40,4061.44,4.93,0.9592,49.54
2,ARIMA,BTC,30,520,6718.69,9436.64,11.33,0.7738,54.04
3,ARIMA,ETH,1,549,58.69,88.83,2.10,0.9842,50.82
4,ARIMA,ETH,7,543,169.73,238.99,6.04,0.8858,50.64
5,ARIMA,ETH,30,520,360.63,483.91,12.44,0.5269,50.19
6,ARIMA,BNB,1,549,9.12,14.55,1.94,0.9929,52.09
7,ARIMA,BNB,7,543,25.15,36.76,5.30,0.9543,51.57
8,ARIMA,BNB,30,520,44.09,68.03,9.57,0.8406,52.12

ARIMA predictions and metrics saved.
Predictions: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results/arima_predictions.csv
Metrics: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results/arima_metrics.csv

In [19]:
print("ARIMA predictions shape:", arima_predictions_df.shape)
print("ARIMA metrics shape:", arima_metrics_df.shape)

print("\nPredictions preview:")
display(arima_predictions_df.head())

print("\nMetrics:")
display(arima_metrics_df)

print("\nFiles saved in:")
print(RESULTS_DIR)

ARIMA predictions shape: (4836, 8)
ARIMA metrics shape: (9, 9)

Predictions preview:

,date,origin_date,asset,horizon,actual,origin_price,arima_pred,model
0,2023-07-01,2023-06-30,BTC,1,30590.078125,30477.251953,30480.008351,ARIMA
1,2023-07-02,2023-07-01,BTC,1,30620.769531,30590.078125,30576.187404,ARIMA
2,2023-07-03,2023-07-02,BTC,1,31156.439453,30620.769531,30630.092230,ARIMA
3,2023-07-04,2023-07-03,BTC,1,30777.582031,31156.439453,31146.697674,ARIMA
4,2023-07-05,2023-07-04,BTC,1,30514.166016,30777.582031,30800.618460,ARIMA

Metrics:

,model,asset,horizon,n_predictions,MAE,RMSE,MAPE,R2,Directional_Accuracy
0,ARIMA,BTC,1,549,1029.50,1567.23,1.77,0.9940,48.63
1,ARIMA,BTC,7,543,2845.40,4061.44,4.93,0.9592,49.54
2,ARIMA,BTC,30,520,6718.69,9436.64,11.33,0.7738,54.04
3,ARIMA,ETH,1,549,58.69,88.83,2.10,0.9842,50.82
4,ARIMA,ETH,7,543,169.73,238.99,6.04,0.8858,50.64
5,ARIMA,ETH,30,520,360.63,483.91,12.44,0.5269,50.19
6,ARIMA,BNB,1,549,9.12,14.55,1.94,0.9929,52.09
7,ARIMA,BNB,7,543,25.15,36.76,5.30,0.9543,51.57
8,ARIMA,BNB,30,520,44.09,68.03,9.57,0.8406,52.12

Files saved in:
/content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results

In [20]:
import random
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

LOOKBACK = 60
BATCH_SIZE = 64
EPOCHS = 80
PATIENCE = 12
LR = 1e-3
HIDDEN_SIZE = 128
NUM_LAYERS = 2
DROPOUT = 0.2

FEATURE_COLS = [c for c in df.columns if c != "date"]
TARGET_COLS = ["BTC_close", "ETH_close", "BNB_close"]
TARGET_IDXS = [FEATURE_COLS.index(c) for c in TARGET_COLS]

print("Device:", DEVICE)
print("Number of features:", len(FEATURE_COLS))
print("Target columns:", TARGET_COLS)

Device: cuda
Number of features: 50
Target columns: ['BTC_close', 'ETH_close', 'BNB_close']

In [21]:
def inverse_transform_targets(values_scaled, scaler, target_indices):
    """
    Kthen parashikimet nga shkalla [0,1] në vlera reale USD
    vetëm për target columns.
    """
    values_scaled = np.asarray(values_scaled)
    output = np.zeros_like(values_scaled, dtype=float)

    for j, idx in enumerate(target_indices):
        data_min = scaler.data_min_[idx]
        data_max = scaler.data_max_[idx]
        output[:, j] = values_scaled[:, j] * (data_max - data_min) + data_min

    return output


def make_sequences_for_split(full_raw_df, full_scaled, target_start, target_end, lookback, horizon):
    """
    Krijon sekuenca me target brenda split-it të kërkuar.

    Input-i për çdo parashikim mbaron në origin_date.
    Target-i është origin_date + horizon.

    Kjo lejon që për Validation/Test të përdoret historia e mëparshme,
    por jo informacion nga e ardhmja.
    """
    X, y, meta = [], [], []

    target_start = pd.to_datetime(target_start)
    target_end = pd.to_datetime(target_end)

    for origin_idx in range(lookback - 1, len(full_raw_df) - horizon):
        target_idx = origin_idx + horizon

        target_date = full_raw_df.iloc[target_idx]["date"]
        origin_date = full_raw_df.iloc[origin_idx]["date"]

        if target_start <= target_date <= target_end:
            X.append(full_scaled[origin_idx - lookback + 1 : origin_idx + 1])
            y.append(full_scaled[target_idx, TARGET_IDXS])

            meta.append({
                "origin_idx": origin_idx,
                "target_idx": target_idx,
                "origin_date": origin_date,
                "date": target_date
            })

    X = np.array(X, dtype=np.float32)
    y = np.array(y, dtype=np.float32)
    meta_df = pd.DataFrame(meta)

    return X, y, meta_df


class CryptoSequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


class LSTMForecastModel(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=2, output_size=3, dropout=0.2):
        super().__init__()

        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0
        )

        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        last_hidden = lstm_out[:, -1, :]
        out = self.dropout(last_hidden)
        return self.fc(out)


print("LSTM helper functions ready.")

LSTM helper functions ready.

In [22]:
def train_lstm_for_horizon(horizon):
    print("\n" + "="*70)
    print(f"Training LSTM for horizon H={horizon}")
    print("="*70)

    # Scaler fit vetëm mbi Train
    scaler = MinMaxScaler()
    scaler.fit(train_df[FEATURE_COLS])

    full_scaled = scaler.transform(df[FEATURE_COLS])

    train_target_start = train_df["date"].iloc[horizon - 1]
    val_target_start = val_df["date"].iloc[horizon - 1]
    test_target_start = test_df["date"].iloc[horizon - 1]

    X_train, y_train, meta_train = make_sequences_for_split(
        full_raw_df=df,
        full_scaled=full_scaled,
        target_start=train_target_start,
        target_end=train_df["date"].max(),
        lookback=LOOKBACK,
        horizon=horizon
    )

    X_val, y_val, meta_val = make_sequences_for_split(
        full_raw_df=df,
        full_scaled=full_scaled,
        target_start=val_target_start,
        target_end=val_df["date"].max(),
        lookback=LOOKBACK,
        horizon=horizon
    )

    X_test, y_test, meta_test = make_sequences_for_split(
        full_raw_df=df,
        full_scaled=full_scaled,
        target_start=test_target_start,
        target_end=test_df["date"].max(),
        lookback=LOOKBACK,
        horizon=horizon
    )
    print("X_train:", X_train.shape, "y_train:", y_train.shape)
    print("X_val:  ", X_val.shape, "y_val:  ", y_val.shape)
    print("X_test: ", X_test.shape, "y_test: ", y_test.shape)

    train_loader = DataLoader(
        CryptoSequenceDataset(X_train, y_train),
        batch_size=BATCH_SIZE,
        shuffle=True,
        drop_last=False
    )

    val_loader = DataLoader(
        CryptoSequenceDataset(X_val, y_val),
        batch_size=BATCH_SIZE,
        shuffle=False,
        drop_last=False
    )

    test_loader = DataLoader(
        CryptoSequenceDataset(X_test, y_test),
        batch_size=BATCH_SIZE,
        shuffle=False,
        drop_last=False
    )

    model = LSTMForecastModel(
        input_size=len(FEATURE_COLS),
        hidden_size=HIDDEN_SIZE,
        num_layers=NUM_LAYERS,
        output_size=len(TARGET_COLS),
        dropout=DROPOUT
    ).to(DEVICE)

    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    criterion = nn.MSELoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        patience=5,
        factor=0.5
    )

    best_val_loss = float("inf")
    best_state = None
    patience_counter = 0

    history = []

    for epoch in range(1, EPOCHS + 1):
        model.train()
        train_losses = []

        for xb, yb in train_loader:
            xb = xb.to(DEVICE)
            yb = yb.to(DEVICE)

            optimizer.zero_grad()
            preds = model(xb)
            loss = criterion(preds, yb)
            loss.backward()

            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()
            train_losses.append(loss.item())

        train_loss = float(np.mean(train_losses))

        model.eval()
        val_losses = []

        with torch.no_grad():
            for xb, yb in val_loader:
                xb = xb.to(DEVICE)
                yb = yb.to(DEVICE)

                preds = model(xb)
                loss = criterion(preds, yb)
                val_losses.append(loss.item())

        val_loss = float(np.mean(val_losses))
        scheduler.step(val_loss)

        history.append({
            "horizon": horizon,
            "epoch": epoch,
            "train_loss": train_loss,
            "val_loss": val_loss
        })

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            patience_counter = 0
        else:
            patience_counter += 1

        if epoch % 5 == 0 or epoch == 1:
            print(f"Epoch {epoch:03d} | Train Loss: {train_loss:.6f} | Val Loss: {val_loss:.6f}")

        if patience_counter >= PATIENCE:
            print(f"Early stopping at epoch {epoch}. Best val loss: {best_val_loss:.6f}")
            break

    model.load_state_dict(best_state)
    model.to(DEVICE)
    model.eval()

    all_preds_scaled = []

    with torch.no_grad():
        for xb, _ in test_loader:
            xb = xb.to(DEVICE)
            preds = model(xb).cpu().numpy()
            all_preds_scaled.append(preds)

    preds_scaled = np.vstack(all_preds_scaled)

    preds_usd = inverse_transform_targets(preds_scaled, scaler, TARGET_IDXS)
    actual_usd = inverse_transform_targets(y_test, scaler, TARGET_IDXS)

    return {
        "horizon": horizon,
        "model": model,
        "scaler": scaler,
        "history": pd.DataFrame(history),
        "meta_test": meta_test,
        "preds_usd": preds_usd,
        "actual_usd": actual_usd
    }


lstm_outputs = []

for horizon in HORIZONS:
    output = train_lstm_for_horizon(horizon)
    lstm_outputs.append(output)

print("All LSTM horizons completed.")

======================================================================
Training LSTM for horizon H=1
======================================================================
X_train: (1351, 60, 50) y_train: (1351, 3)
X_val:   (181, 60, 50) y_val:   (181, 3)
X_test:  (549, 60, 50) y_test:  (549, 3)
Epoch 001 | Train Loss: 0.042956 | Val Loss: 0.014447
Epoch 005 | Train Loss: 0.003434 | Val Loss: 0.001937
Epoch 010 | Train Loss: 0.002302 | Val Loss: 0.000865
Epoch 015 | Train Loss: 0.002126 | Val Loss: 0.001280
Epoch 020 | Train Loss: 0.001878 | Val Loss: 0.000657
Epoch 025 | Train Loss: 0.001529 | Val Loss: 0.000472
Epoch 030 | Train Loss: 0.001594 | Val Loss: 0.000480
Epoch 035 | Train Loss: 0.001558 | Val Loss: 0.000588
Epoch 040 | Train Loss: 0.001331 | Val Loss: 0.000417
Early stopping at epoch 43. Best val loss: 0.000348

======================================================================
Training LSTM for horizon H=7
======================================================================
X_train: (1345, 60, 50) y_train: (1345, 3)
X_val:   (175, 60, 50) y_val:   (175, 3)
X_test:  (543, 60, 50) y_test:  (543, 3)
Epoch 001 | Train Loss: 0.035667 | Val Loss: 0.015561
Epoch 005 | Train Loss: 0.004575 | Val Loss: 0.003195
Epoch 010 | Train Loss: 0.003282 | Val Loss: 0.001805
Epoch 015 | Train Loss: 0.003024 | Val Loss: 0.002934
Epoch 020 | Train Loss: 0.002566 | Val Loss: 0.001611
Epoch 025 | Train Loss: 0.002772 | Val Loss: 0.001344
Epoch 030 | Train Loss: 0.002659 | Val Loss: 0.001322
Epoch 035 | Train Loss: 0.002649 | Val Loss: 0.001287
Epoch 040 | Train Loss: 0.002130 | Val Loss: 0.001032
Epoch 045 | Train Loss: 0.002911 | Val Loss: 0.001360
Epoch 050 | Train Loss: 0.001815 | Val Loss: 0.001214
Epoch 055 | Train Loss: 0.001896 | Val Loss: 0.001050
Epoch 060 | Train Loss: 0.001681 | Val Loss: 0.001112
Early stopping at epoch 64. Best val loss: 0.000985

======================================================================
Training LSTM for horizon H=30
======================================================================
X_train: (1322, 60, 50) y_train: (1322, 3)
X_val:   (152, 60, 50) y_val:   (152, 3)
X_test:  (520, 60, 50) y_test:  (520, 3)
Epoch 001 | Train Loss: 0.054564 | Val Loss: 0.005185
Epoch 005 | Train Loss: 0.009415 | Val Loss: 0.005442
Epoch 010 | Train Loss: 0.005742 | Val Loss: 0.005916
Early stopping at epoch 13. Best val loss: 0.005185
All LSTM horizons completed.

In [23]:
lstm_predictions_rows = []
lstm_metrics_rows = []
lstm_history_all = []

for output in lstm_outputs:
    horizon = output["horizon"]
    meta_test = output["meta_test"]
    preds_usd = output["preds_usd"]
    actual_usd = output["actual_usd"]

    history_df = output["history"].copy()
    lstm_history_all.append(history_df)

    for asset_idx, asset in enumerate(["BTC", "ETH", "BNB"]):
        target_col = f"{asset}_close"

        asset_actual = actual_usd[:, asset_idx]
        asset_pred = preds_usd[:, asset_idx]

        origin_prices = []
        origin_dates = []
        target_dates = []

        for _, mrow in meta_test.iterrows():
            origin_idx = int(mrow["origin_idx"])
            origin_prices.append(float(df.iloc[origin_idx][target_col]))
            origin_dates.append(mrow["origin_date"])
            target_dates.append(mrow["date"])

        asset_pred_df = pd.DataFrame({
            "date": target_dates,
            "origin_date": origin_dates,
            "asset": asset,
            "horizon": horizon,
            "actual": asset_actual,
            "origin_price": origin_prices,
            "lstm_pred": asset_pred,
            "model": "LSTM"
        })

        metrics = compute_forecast_metrics(
            y_true=asset_pred_df["actual"],
            y_pred=asset_pred_df["lstm_pred"],
            origin_price=asset_pred_df["origin_price"]
        )

        metrics_row = {
            "model": "LSTM",
            "asset": asset,
            "horizon": horizon,
            "n_predictions": len(asset_pred_df),
            **metrics
        }

        lstm_predictions_rows.append(asset_pred_df)
        lstm_metrics_rows.append(metrics_row)

lstm_predictions_df = pd.concat(lstm_predictions_rows, ignore_index=True)
lstm_metrics_df = pd.DataFrame(lstm_metrics_rows)
lstm_history_df = pd.concat(lstm_history_all, ignore_index=True)

display(lstm_metrics_df)

lstm_predictions_df.to_csv(RESULTS_DIR / "lstm_predictions.csv", index=False)
lstm_metrics_df.to_csv(RESULTS_DIR / "lstm_metrics.csv", index=False)
lstm_history_df.to_csv(RESULTS_DIR / "lstm_training_history.csv", index=False)

print("LSTM predictions saved:", RESULTS_DIR / "lstm_predictions.csv")
print("LSTM metrics saved:", RESULTS_DIR / "lstm_metrics.csv")
print("LSTM history saved:", RESULTS_DIR / "lstm_training_history.csv")

,model,asset,horizon,n_predictions,MAE,RMSE,MAPE,R2,Directional_Accuracy
0,LSTM,BTC,1,549,5591.40,7562.49,8.75,0.8593,50.09
1,LSTM,ETH,1,549,192.19,258.41,7.15,0.8666,53.19
2,LSTM,BNB,1,549,22.57,27.38,6.46,0.9747,54.10
3,LSTM,BTC,7,543,9613.03,12000.61,16.59,0.6439,51.57
4,LSTM,ETH,7,543,599.68,771.00,21.89,-0.1886,52.67
5,LSTM,BNB,7,543,59.74,68.98,17.07,0.8390,55.62
6,LSTM,BTC,30,520,13218.08,17537.82,20.73,0.2189,35.38
7,LSTM,ETH,30,520,625.63,801.36,22.80,-0.2973,51.54
8,LSTM,BNB,30,520,47.34,60.85,11.01,0.8725,53.85

LSTM predictions saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results/lstm_predictions.csv
LSTM metrics saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results/lstm_metrics.csv
LSTM history saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results/lstm_training_history.csv

In [24]:
print("LSTM predictions shape:", lstm_predictions_df.shape)
print("LSTM metrics shape:", lstm_metrics_df.shape)

print("\nLSTM predictions preview:")
display(lstm_predictions_df.head())

print("\nLSTM metrics:")
display(lstm_metrics_df)

LSTM predictions shape: (4836, 8)
LSTM metrics shape: (9, 9)

LSTM predictions preview:

,date,origin_date,asset,horizon,actual,origin_price,lstm_pred,model
0,2023-07-01,2023-06-30,BTC,1,30590.078840,30477.251953,32454.045759,LSTM
1,2023-07-02,2023-07-01,BTC,1,30620.769781,30590.078125,32877.805120,LSTM
2,2023-07-03,2023-07-02,BTC,1,31156.438883,30620.769531,32968.316772,LSTM
3,2023-07-04,2023-07-03,BTC,1,30777.582612,31156.439453,33388.784558,LSTM
4,2023-07-05,2023-07-04,BTC,1,30514.165351,30777.582031,33454.441112,LSTM

LSTM metrics:

,model,asset,horizon,n_predictions,MAE,RMSE,MAPE,R2,Directional_Accuracy
0,LSTM,BTC,1,549,5591.40,7562.49,8.75,0.8593,50.09
1,LSTM,ETH,1,549,192.19,258.41,7.15,0.8666,53.19
2,LSTM,BNB,1,549,22.57,27.38,6.46,0.9747,54.10
3,LSTM,BTC,7,543,9613.03,12000.61,16.59,0.6439,51.57
4,LSTM,ETH,7,543,599.68,771.00,21.89,-0.1886,52.67
5,LSTM,BNB,7,543,59.74,68.98,17.07,0.8390,55.62
6,LSTM,BTC,30,520,13218.08,17537.82,20.73,0.2189,35.38
7,LSTM,ETH,30,520,625.63,801.36,22.80,-0.2973,51.54
8,LSTM,BNB,30,520,47.34,60.85,11.01,0.8725,53.85

In [25]:
!pip -q install pytorch-forecasting lightning

import torch
import lightning.pytorch as pl
import pytorch_forecasting

print("torch:", torch.__version__)
print("lightning:", pl.__version__)
print("pytorch_forecasting:", pytorch_forecasting.__version__)
print("GPU:", torch.cuda.is_available())

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.1/403.1 kB 36.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 848.6/848.6 kB 61.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.8/160.8 kB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 69.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 59.7 MB/s eta 0:00:00
torch: 2.11.0+cu128
lightning: 2.6.5
pytorch_forecasting: 1.7.0
GPU: True

In [32]:
!pip -q install pytorch-forecasting lightning

import torch
import lightning.pytorch as pl
from lightning.pytorch.callbacks import EarlyStopping
from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.metrics import QuantileLoss

try:
    from pytorch_forecasting.data import EncoderNormalizer
except ImportError:
    from pytorch_forecasting.data.encoders import EncoderNormalizer

pl.seed_everything(42, workers=True)

QUANTILES = [0.1, 0.5, 0.9]

print("TFT setup completed.")
print("GPU available:", torch.cuda.is_available())

INFO: Seed set to 42
INFO:lightning.fabric.utilities.seed:Seed set to 42

TFT setup completed.
GPU available: True

In [33]:
def build_tft_multiasset_return_dataframe(df):
    rows = []

    for asset in ["BTC", "ETH", "BNB"]:
        temp = pd.DataFrame()
        temp["date"] = df["date"]
        temp["asset"] = asset

        temp["close"] = df[f"{asset}_close"]
        temp["log_close"] = np.log(df[f"{asset}_close"])
        temp["target_return"] = temp["log_close"].diff()

        temp["open"] = df[f"{asset}_open"]
        temp["high"] = df[f"{asset}_high"]
        temp["low"] = df[f"{asset}_low"]
        temp["volume"] = df[f"{asset}_volume"]

        temp["RSI14"] = df[f"{asset}_RSI14"]
        temp["EMA7"] = df[f"{asset}_EMA7"]
        temp["EMA21"] = df[f"{asset}_EMA21"]
        temp["EMA50"] = df[f"{asset}_EMA50"]
        temp["MACD"] = df[f"{asset}_MACD"]
        temp["MACD_signal"] = df[f"{asset}_MACD_signal"]
        temp["BB_width"] = df[f"{asset}_BB_width"]

        temp["return1d"] = df[f"{asset}_return1d"]
        temp["vol7d"] = df[f"{asset}_vol7d"]

        temp["BTC_close_global"] = df["BTC_close"]
        temp["ETH_close_global"] = df["ETH_close"]
        temp["BNB_close_global"] = df["BNB_close"]

        temp["BTC_return_global"] = df["BTC_return1d"]
        temp["ETH_return_global"] = df["ETH_return1d"]
        temp["BNB_return_global"] = df["BNB_return1d"]

        temp["fear_greed"] = df["fear_greed"]
        temp["corr_BTC_ETH_30d"] = df["corr_BTC_ETH_30d"]
        temp["corr_BTC_BNB_30d"] = df["corr_BTC_BNB_30d"]
        temp["corr_ETH_BNB_30d"] = df["corr_ETH_BNB_30d"]

        temp["day_of_week"] = df["day_of_week"].astype(int)
        temp["month"] = df["month"].astype(int)
        temp["quarter"] = df["quarter"].astype(int)
        temp["is_weekend"] = df["is_weekend"].astype(int)

        rows.append(temp)

    out = pd.concat(rows, ignore_index=True)
    out["date"] = pd.to_datetime(out["date"])
    out = out.dropna().sort_values(["asset", "date"]).reset_index(drop=True)
    out["time_idx"] = (out["date"] - out["date"].min()).dt.days

    return out


tft_ret_df = build_tft_multiasset_return_dataframe(df)

print("TFT_LOG_RETURN dataset shape:", tft_ret_df.shape)
print("Date range:", tft_ret_df["date"].min().date(), "to", tft_ret_df["date"].max().date())
print("Rows per asset:")
display(tft_ret_df.groupby("asset").size())

tft_ret_df.to_csv(DATA_DIR / "tft_log_return_long_dataset.csv", index=False)
print("Saved:", DATA_DIR / "tft_log_return_long_dataset.csv")

TFT_LOG_RETURN dataset shape: (6420, 33)
Date range: 2019-02-21 to 2024-12-30
Rows per asset:

asset
BNB    2140
BTC    2140
ETH    2140
dtype: int64

Saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/02_Data/tft_log_return_long_dataset.csv

In [34]:
RET_KNOWN_REALS = [
    "time_idx",
    "day_of_week",
    "month",
    "quarter",
    "is_weekend"
]

RET_UNKNOWN_REALS = [
    "target_return",
    "open",
    "high",
    "low",
    "volume",
    "RSI14",
    "EMA7",
    "EMA21",
    "EMA50",
    "MACD",
    "MACD_signal",
    "BB_width",
    "return1d",
    "vol7d",
    "fear_greed",
    "corr_BTC_ETH_30d",
    "corr_BTC_BNB_30d",
    "corr_ETH_BNB_30d",
    "BTC_close_global",
    "ETH_close_global",
    "BNB_close_global",
    "BTC_return_global",
    "ETH_return_global",
    "BNB_return_global"
]

def get_ret_time_idx(date_value):
    date_value = pd.to_datetime(date_value)
    return int((date_value - tft_ret_df["date"].min()).days)

RET_TRAIN_END_IDX = get_ret_time_idx("2022-12-31")
RET_VAL_START_IDX = get_ret_time_idx("2023-01-01")
RET_VAL_END_IDX = get_ret_time_idx("2023-06-30")
RET_TEST_START_IDX = get_ret_time_idx("2023-07-01")
RET_TEST_END_IDX = get_ret_time_idx("2024-12-30")

def build_multiasset_return_tft_datasets(horizon):
    training = TimeSeriesDataSet(
        tft_ret_df[tft_ret_df["time_idx"] <= RET_TRAIN_END_IDX],
        time_idx="time_idx",
        target="target_return",
        group_ids=["asset"],
        min_encoder_length=60,
        max_encoder_length=60,
        min_prediction_length=horizon,
        max_prediction_length=horizon,
        static_categoricals=["asset"],
        time_varying_known_reals=RET_KNOWN_REALS,
        time_varying_unknown_reals=RET_UNKNOWN_REALS,
        target_normalizer=EncoderNormalizer(
            method="standard",
            transformation=None,
            max_length=60
        ),
        add_relative_time_idx=True,
        add_target_scales=True,
        add_encoder_length=True,
        allow_missing_timesteps=False
    )

    validation = TimeSeriesDataSet.from_dataset(
        training,
        tft_ret_df[tft_ret_df["time_idx"] <= RET_VAL_END_IDX],
        min_prediction_idx=RET_VAL_START_IDX,
        stop_randomization=True
    )

    testing = TimeSeriesDataSet.from_dataset(
        training,
        tft_ret_df[tft_ret_df["time_idx"] <= RET_TEST_END_IDX],
        min_prediction_idx=RET_TEST_START_IDX,
        stop_randomization=True
    )

    return training, validation, testing

print("TFT_LOG_RETURN dataset functions ready.")

TFT_LOG_RETURN dataset functions ready.

In [35]:
def train_multiasset_return_tft(horizon):
    print("\n" + "="*70)
    print(f"Training TFT_LOG_RETURN for H={horizon}")
    print("="*70)

    training, validation, testing = build_multiasset_return_tft_datasets(horizon)

    train_loader = training.to_dataloader(
        train=True,
        batch_size=64,
        num_workers=0
    )

    val_loader = validation.to_dataloader(
        train=False,
        batch_size=64,
        num_workers=0
    )

    test_loader = testing.to_dataloader(
        train=False,
        batch_size=64,
        num_workers=0
    )

    model = TemporalFusionTransformer.from_dataset(
        training,
        learning_rate=1e-3,
        hidden_size=64,
        attention_head_size=4,
        dropout=0.1,
        hidden_continuous_size=32,
        output_size=len(QUANTILES),
        loss=QuantileLoss(quantiles=QUANTILES),
        reduce_on_plateau_patience=4
    )

    print(f"TFT_LOG_RETURN parameters: {model.size()/1e3:.1f}k")

    early_stop_callback = EarlyStopping(
        monitor="val_loss",
        min_delta=1e-4,
        patience=8,
        verbose=True,
        mode="min"
    )

    trainer = pl.Trainer(
        max_epochs=50,
        accelerator="gpu" if torch.cuda.is_available() else "cpu",
        devices=1,
        gradient_clip_val=0.1,
        callbacks=[early_stop_callback],
        enable_progress_bar=True,
        enable_model_summary=False,
        logger=False
    )

    trainer.fit(
        model,
        train_dataloaders=train_loader,
        val_dataloaders=val_loader
    )

    return model, testing, test_loader

print("TFT_LOG_RETURN training function ready.")

TFT_LOG_RETURN training function ready.

In [36]:
tft_ret_h1_model, tft_ret_h1_testing, tft_ret_h1_loader = train_multiasset_return_tft(1)
print("TFT_LOG_RETURN H=1 completed.")

tft_ret_h7_model, tft_ret_h7_testing, tft_ret_h7_loader = train_multiasset_return_tft(7)
print("TFT_LOG_RETURN H=7 completed.")

tft_ret_h30_model, tft_ret_h30_testing, tft_ret_h30_loader = train_multiasset_return_tft(30)
print("TFT_LOG_RETURN H=30 completed.")

======================================================================
Training TFT_LOG_RETURN for H=1
======================================================================

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

TFT_LOG_RETURN parameters: 505.0k

INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Output()

INFO: Metric val_loss improved. New best score: 0.013
INFO:lightning.pytorch.callbacks.early_stopping:Metric val_loss improved. New best score: 0.013
INFO: Monitored metric val_loss did not improve in the last 8 records. Best score: 0.013. Signaling Trainer to stop.
INFO:lightning.pytorch.callbacks.early_stopping:Monitored metric val_loss did not improve in the last 8 records. Best score: 0.013. Signaling Trainer to stop.

TFT_LOG_RETURN H=1 completed.

======================================================================
Training TFT_LOG_RETURN for H=7
======================================================================

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Output()

TFT_LOG_RETURN parameters: 505.0k

INFO: Metric val_loss improved. New best score: 0.013
INFO:lightning.pytorch.callbacks.early_stopping:Metric val_loss improved. New best score: 0.013
INFO: Monitored metric val_loss did not improve in the last 8 records. Best score: 0.013. Signaling Trainer to stop.
INFO:lightning.pytorch.callbacks.early_stopping:Monitored metric val_loss did not improve in the last 8 records. Best score: 0.013. Signaling Trainer to stop.

TFT_LOG_RETURN H=7 completed.

======================================================================
Training TFT_LOG_RETURN for H=30
======================================================================

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Output()

TFT_LOG_RETURN parameters: 505.0k

INFO: Metric val_loss improved. New best score: 0.013
INFO:lightning.pytorch.callbacks.early_stopping:Metric val_loss improved. New best score: 0.013
INFO: Monitored metric val_loss did not improve in the last 8 records. Best score: 0.013. Signaling Trainer to stop.
INFO:lightning.pytorch.callbacks.early_stopping:Monitored metric val_loss did not improve in the last 8 records. Best score: 0.013. Signaling Trainer to stop.

TFT_LOG_RETURN H=30 completed.

In [37]:
def extract_multiasset_return_tft_predictions_cumulative(model, testing_dataset, test_loader, horizon):
    prediction = model.predict(
        test_loader,
        mode="quantiles",
        return_x=True,
        trainer_kwargs={
            "accelerator": "gpu" if torch.cuda.is_available() else "cpu",
            "devices": 1
        }
    )

    output = prediction.output
    if hasattr(output, "detach"):
        output = output.detach().cpu().numpy()

    p50_return = output[:, :, 1]

    x = prediction.x
    decoder_time_idx = x["decoder_time_idx"].detach().cpu().numpy()

    target_time_idx = decoder_time_idx[:, -1]
    origin_time_idx = target_time_idx - horizon

    index_df = testing_dataset.x_to_index(x)

    records = []

    for i in range(len(index_df)):
        asset = str(index_df.iloc[i]["asset"])

        target_idx = int(target_time_idx[i])
        origin_idx = int(origin_time_idx[i])

        actual_row = tft_ret_df[
            (tft_ret_df["asset"] == asset) &
            (tft_ret_df["time_idx"] == target_idx)
        ]

        origin_row = tft_ret_df[
            (tft_ret_df["asset"] == asset) &
            (tft_ret_df["time_idx"] == origin_idx)
        ]

        if actual_row.empty or origin_row.empty:
            continue

        origin_price = float(origin_row["close"].iloc[0])
        actual_price = float(actual_row["close"].iloc[0])

        predicted_cumulative_return = float(np.sum(p50_return[i, :]))
        predicted_price = origin_price * np.exp(predicted_cumulative_return)

        actual_cumulative_return = float(np.log(actual_price / origin_price))

        records.append({
            "date": actual_row["date"].iloc[0],
            "origin_date": origin_row["date"].iloc[0],
            "asset": asset,
            "horizon": horizon,
            "actual": actual_price,
            "origin_price": origin_price,
            "actual_cumulative_return": actual_cumulative_return,
            "predicted_cumulative_return": predicted_cumulative_return,
            "tft_pred": predicted_price,
            "model": "TFT_LOG_RETURN"
        })

    return pd.DataFrame(records)


def evaluate_tft_log_return_predictions(pred_df, horizon):
    rows = []

    for asset in ["BTC", "ETH", "BNB"]:
        temp = pred_df[pred_df["asset"] == asset].copy()

        metrics = compute_forecast_metrics(
            y_true=temp["actual"],
            y_pred=temp["tft_pred"],
            origin_price=temp["origin_price"]
        )

        rows.append({
            "model": "TFT_LOG_RETURN",
            "asset": asset,
            "horizon": horizon,
            "n_predictions": len(temp),
            **metrics
        })

    return pd.DataFrame(rows)

print("TFT_LOG_RETURN prediction functions ready.")

TFT_LOG_RETURN prediction functions ready.

In [38]:
tft_ret_h1_pred_df = extract_multiasset_return_tft_predictions_cumulative(
    model=tft_ret_h1_model,
    testing_dataset=tft_ret_h1_testing,
    test_loader=tft_ret_h1_loader,
    horizon=1
)

tft_ret_h7_pred_df = extract_multiasset_return_tft_predictions_cumulative(
    model=tft_ret_h7_model,
    testing_dataset=tft_ret_h7_testing,
    test_loader=tft_ret_h7_loader,
    horizon=7
)

tft_ret_h30_pred_df = extract_multiasset_return_tft_predictions_cumulative(
    model=tft_ret_h30_model,
    testing_dataset=tft_ret_h30_testing,
    test_loader=tft_ret_h30_loader,
    horizon=30
)

tft_ret_h1_metrics_df = evaluate_tft_log_return_predictions(tft_ret_h1_pred_df, 1)
tft_ret_h7_metrics_df = evaluate_tft_log_return_predictions(tft_ret_h7_pred_df, 7)
tft_ret_h30_metrics_df = evaluate_tft_log_return_predictions(tft_ret_h30_pred_df, 30)

tft_log_return_metrics_all_df = pd.concat([
    tft_ret_h1_metrics_df,
    tft_ret_h7_metrics_df,
    tft_ret_h30_metrics_df
], ignore_index=True)

tft_log_return_predictions_all_df = pd.concat([
    tft_ret_h1_pred_df,
    tft_ret_h7_pred_df,
    tft_ret_h30_pred_df
], ignore_index=True)

display(tft_log_return_metrics_all_df)

tft_log_return_metrics_all_df.to_csv(
    RESULTS_DIR / "tft_log_return_metrics_all_horizons.csv",
    index=False
)

tft_log_return_predictions_all_df.to_csv(
    RESULTS_DIR / "tft_log_return_predictions_all_horizons.csv",
    index=False
)

print("Saved:", RESULTS_DIR / "tft_log_return_metrics_all_horizons.csv")
print("Saved:", RESULTS_DIR / "tft_log_return_predictions_all_horizons.csv")
print("TFT predictions shape:", tft_log_return_predictions_all_df.shape)

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

,model,asset,horizon,n_predictions,MAE,RMSE,MAPE,R2,Directional_Accuracy
0,TFT_LOG_RETURN,BTC,1,549,1070.72,1629.44,1.84,0.9935,49.73
1,TFT_LOG_RETURN,ETH,1,549,59.73,90.17,2.14,0.9838,49.18
2,TFT_LOG_RETURN,BNB,1,549,9.19,14.52,1.95,0.9929,48.09
3,TFT_LOG_RETURN,BTC,7,543,4342.21,5961.05,7.64,0.9121,43.09
4,TFT_LOG_RETURN,ETH,7,543,235.29,322.09,8.52,0.7926,45.49
5,TFT_LOG_RETURN,BNB,7,543,33.42,50.11,7.04,0.9150,51.20
6,TFT_LOG_RETURN,BTC,30,520,11130.91,14841.53,17.99,0.4406,42.88
7,TFT_LOG_RETURN,ETH,30,520,581.55,749.10,20.34,-0.1337,54.81
8,TFT_LOG_RETURN,BNB,30,520,89.46,113.54,18.48,0.5561,46.15

Saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results/tft_log_return_metrics_all_horizons.csv
Saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results/tft_log_return_predictions_all_horizons.csv
TFT predictions shape: (4836, 10)

In [39]:
print((RESULTS_DIR / "tft_log_return_metrics_all_horizons.csv").exists())
print((RESULTS_DIR / "tft_log_return_predictions_all_horizons.csv").exists())

True
True

In [40]:
from pathlib import Path
import pandas as pd
import numpy as np

required_files = [
    RESULTS_DIR / "arima_metrics.csv",
    RESULTS_DIR / "arima_predictions.csv",
    RESULTS_DIR / "lstm_metrics.csv",
    RESULTS_DIR / "lstm_predictions.csv",
    RESULTS_DIR / "tft_log_return_metrics_all_horizons.csv",
    RESULTS_DIR / "tft_log_return_predictions_all_horizons.csv",
]

for f in required_files:
    print(f.name, "EXISTS" if f.exists() else "MISSING")

arima_metrics.csv EXISTS
arima_predictions.csv EXISTS
lstm_metrics.csv EXISTS
lstm_predictions.csv EXISTS
tft_log_return_metrics_all_horizons.csv EXISTS
tft_log_return_predictions_all_horizons.csv EXISTS

In [41]:
# ============================================================
# Final metrics: ARIMA + LSTM + TFT_LOG_RETURN
# ============================================================

arima_metrics_final = pd.read_csv(RESULTS_DIR / "arima_metrics.csv")
lstm_metrics_final = pd.read_csv(RESULTS_DIR / "lstm_metrics.csv")
tft_metrics_final = pd.read_csv(RESULTS_DIR / "tft_log_return_metrics_all_horizons.csv")

final_metrics_all_df = pd.concat(
    [arima_metrics_final, lstm_metrics_final, tft_metrics_final],
    ignore_index=True
)

model_order = {
    "ARIMA": 0,
    "LSTM": 1,
    "TFT_LOG_RETURN": 2
}

asset_order = {
    "BTC": 0,
    "ETH": 1,
    "BNB": 2
}

final_metrics_all_df["model_order"] = final_metrics_all_df["model"].map(model_order)
final_metrics_all_df["asset_order"] = final_metrics_all_df["asset"].map(asset_order)

final_metrics_all_df = final_metrics_all_df.sort_values(
    ["asset_order", "horizon", "model_order"]
).drop(columns=["model_order", "asset_order"]).reset_index(drop=True)

display(final_metrics_all_df)

final_metrics_all_df.to_csv(
    RESULTS_DIR / "final_metrics_arima_lstm_tft.csv",
    index=False
)

print("Saved:", RESULTS_DIR / "final_metrics_arima_lstm_tft.csv")
print("Exists:", (RESULTS_DIR / "final_metrics_arima_lstm_tft.csv").exists())

,model,asset,horizon,n_predictions,MAE,RMSE,MAPE,R2,Directional_Accuracy
0,ARIMA,BTC,1,549,1029.50,1567.23,1.77,0.9940,48.63
1,LSTM,BTC,1,549,5591.40,7562.49,8.75,0.8593,50.09
2,TFT_LOG_RETURN,BTC,1,549,1070.72,1629.44,1.84,0.9935,49.73
3,ARIMA,BTC,7,543,2845.40,4061.44,4.93,0.9592,49.54
4,LSTM,BTC,7,543,9613.03,12000.61,16.59,0.6439,51.57
5,TFT_LOG_RETURN,BTC,7,543,4342.21,5961.05,7.64,0.9121,43.09
6,ARIMA,BTC,30,520,6718.69,9436.64,11.33,0.7738,54.04
7,LSTM,BTC,30,520,13218.08,17537.82,20.73,0.2189,35.38
8,TFT_LOG_RETURN,BTC,30,520,11130.91,14841.53,17.99,0.4406,42.88
9,ARIMA,ETH,1,549,58.69,88.83,2.10,0.9842,50.82
10,LSTM,ETH,1,549,192.19,258.41,7.15,0.8666,53.19
11,TFT_LOG_RETURN,ETH,1,549,59.73,90.17,2.14,0.9838,49.18
12,ARIMA,ETH,7,543,169.73,238.99,6.04,0.8858,50.64
13,LSTM,ETH,7,543,599.68,771.00,21.89,-0.1886,52.67
14,TFT_LOG_RETURN,ETH,7,543,235.29,322.09,8.52,0.7926,45.49
15,ARIMA,ETH,30,520,360.63,483.91,12.44,0.5269,50.19
16,LSTM,ETH,30,520,625.63,801.36,22.80,-0.2973,51.54
17,TFT_LOG_RETURN,ETH,30,520,581.55,749.10,20.34,-0.1337,54.81
18,ARIMA,BNB,1,549,9.12,14.55,1.94,0.9929,52.09
19,LSTM,BNB,1,549,22.57,27.38,6.46,0.9747,54.10
20,TFT_LOG_RETURN,BNB,1,549,9.19,14.52,1.95,0.9929,48.09
21,ARIMA,BNB,7,543,25.15,36.76,5.30,0.9543,51.57
22,LSTM,BNB,7,543,59.74,68.98,17.07,0.8390,55.62
23,TFT_LOG_RETURN,BNB,7,543,33.42,50.11,7.04,0.9150,51.20
24,ARIMA,BNB,30,520,44.09,68.03,9.57,0.8406,52.12
25,LSTM,BNB,30,520,47.34,60.85,11.01,0.8725,53.85
26,TFT_LOG_RETURN,BNB,30,520,89.46,113.54,18.48,0.5561,46.15

Saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results/final_metrics_arima_lstm_tft.csv
Exists: True

In [42]:
# ============================================================
# Combined predictions: ARIMA + LSTM + TFT_LOG_RETURN
# ============================================================

arima_pred_final = pd.read_csv(RESULTS_DIR / "arima_predictions.csv")
lstm_pred_final = pd.read_csv(RESULTS_DIR / "lstm_predictions.csv")
tft_pred_final = pd.read_csv(RESULTS_DIR / "tft_log_return_predictions_all_horizons.csv")

arima_pred_final = arima_pred_final[
    ["date", "origin_date", "asset", "horizon", "actual", "origin_price", "arima_pred"]
].rename(columns={
    "actual": "actual_arima",
    "origin_price": "origin_price_arima"
})

lstm_pred_final = lstm_pred_final[
    ["date", "origin_date", "asset", "horizon", "actual", "origin_price", "lstm_pred"]
].rename(columns={
    "actual": "actual_lstm",
    "origin_price": "origin_price_lstm"
})

tft_pred_final = tft_pred_final[
    ["date", "origin_date", "asset", "horizon", "actual", "origin_price", "tft_pred"]
].rename(columns={
    "actual": "actual_tft",
    "origin_price": "origin_price_tft"
})

for temp_df in [arima_pred_final, lstm_pred_final, tft_pred_final]:
    temp_df["date"] = pd.to_datetime(temp_df["date"])
    temp_df["origin_date"] = pd.to_datetime(temp_df["origin_date"])
    temp_df["asset"] = temp_df["asset"].astype(str)
    temp_df["horizon"] = temp_df["horizon"].astype(int)

combined_predictions_df = arima_pred_final.merge(
    lstm_pred_final,
    on=["date", "origin_date", "asset", "horizon"],
    how="inner"
)

combined_predictions_df = combined_predictions_df.merge(
    tft_pred_final,
    on=["date", "origin_date", "asset", "horizon"],
    how="inner"
)

combined_predictions_df["actual_diff_arima_lstm"] = (
    combined_predictions_df["actual_arima"] - combined_predictions_df["actual_lstm"]
).abs()

combined_predictions_df["actual_diff_arima_tft"] = (
    combined_predictions_df["actual_arima"] - combined_predictions_df["actual_tft"]
).abs()

combined_predictions_df["origin_diff_arima_lstm"] = (
    combined_predictions_df["origin_price_arima"] - combined_predictions_df["origin_price_lstm"]
).abs()

combined_predictions_df["origin_diff_arima_tft"] = (
    combined_predictions_df["origin_price_arima"] - combined_predictions_df["origin_price_tft"]
).abs()

print("Max actual diff ARIMA-LSTM:", combined_predictions_df["actual_diff_arima_lstm"].max())
print("Max actual diff ARIMA-TFT:", combined_predictions_df["actual_diff_arima_tft"].max())
print("Max origin diff ARIMA-LSTM:", combined_predictions_df["origin_diff_arima_lstm"].max())
print("Max origin diff ARIMA-TFT:", combined_predictions_df["origin_diff_arima_tft"].max())

combined_predictions_df["actual"] = combined_predictions_df["actual_arima"]
combined_predictions_df["origin_price"] = combined_predictions_df["origin_price_arima"]

combined_predictions_df = combined_predictions_df[
    [
        "date",
        "origin_date",
        "asset",
        "horizon",
        "actual",
        "origin_price",
        "arima_pred",
        "lstm_pred",
        "tft_pred"
    ]
].sort_values(["asset", "horizon", "date"]).reset_index(drop=True)

display(combined_predictions_df.head())
print("Combined predictions shape:", combined_predictions_df.shape)

combined_predictions_df.to_csv(
    RESULTS_DIR / "combined_predictions_arima_lstm_tft.csv",
    index=False
)

print("Saved:", RESULTS_DIR / "combined_predictions_arima_lstm_tft.csv")
print("Exists:", (RESULTS_DIR / "combined_predictions_arima_lstm_tft.csv").exists())

Max actual diff ARIMA-LSTM: 0.0037994327722117305
Max actual diff ARIMA-TFT: 0.0
Max origin diff ARIMA-LSTM: 0.0
Max origin diff ARIMA-TFT: 0.0

,date,origin_date,asset,horizon,actual,origin_price,arima_pred,lstm_pred,tft_pred
0,2023-07-01,2023-06-30,BNB,1,247.759430,240.369781,239.716061,258.511625,239.445368
1,2023-07-02,2023-07-01,BNB,1,246.257919,247.759430,247.230284,264.335075,246.813661
2,2023-07-03,2023-07-02,BNB,1,246.382217,246.257919,248.495297,267.614060,245.354213
3,2023-07-04,2023-07-03,BNB,1,242.492920,246.382217,246.249712,272.593379,245.152940
4,2023-07-05,2023-07-04,BNB,1,239.081085,242.492920,242.287807,273.895497,241.470533

Combined predictions shape: (4836, 9)
Saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/04_Results/combined_predictions_arima_lstm_tft.csv
Exists: True

In [43]:
# ============================================================
# Diebold-Mariano Test + Wilcoxon Signed-Rank Test
# ============================================================

from scipy import stats

def diebold_mariano_test(e1, e2, horizon=1, power=2):
    """
    e1 = actual - prediction_model_a
    e2 = actual - prediction_model_b

    Negative DM => model_a has lower loss than model_b.
    Positive DM => model_b has lower loss than model_a.
    """
    e1 = np.asarray(e1, dtype=float)
    e2 = np.asarray(e2, dtype=float)

    if power == 2:
        d = e1**2 - e2**2
    elif power == 1:
        d = np.abs(e1) - np.abs(e2)
    else:
        raise ValueError("power must be 1 or 2")

    d = d[~np.isnan(d)]
    n = len(d)

    if n < 5:
        return np.nan, np.nan

    d_mean = np.mean(d)

    lag = max(horizon - 1, 0)
    gamma0 = np.var(d, ddof=1)
    var_d = gamma0

    for l in range(1, lag + 1):
        cov = np.cov(d[l:], d[:-l], ddof=1)[0, 1]
        weight = 1 - l / (lag + 1)
        var_d += 2 * weight * cov

    if var_d <= 0 or np.isnan(var_d):
        return np.nan, np.nan

    dm_stat = d_mean / np.sqrt(var_d / n)
    p_value = 2 * (1 - stats.norm.cdf(abs(dm_stat)))

    return float(dm_stat), float(p_value)


def run_statistical_tests(pred_df):
    rows = []

    model_pairs = [
        ("TFT_LOG_RETURN", "ARIMA", "tft_pred", "arima_pred"),
        ("TFT_LOG_RETURN", "LSTM", "tft_pred", "lstm_pred"),
        ("LSTM", "ARIMA", "lstm_pred", "arima_pred"),
    ]

    for asset in ["BTC", "ETH", "BNB"]:
        for horizon in [1, 7, 30]:
            temp = pred_df[
                (pred_df["asset"] == asset) &
                (pred_df["horizon"] == horizon)
            ].copy()

            actual = temp["actual"].values

            for model_a, model_b, pred_a_col, pred_b_col in model_pairs:
                pred_a = temp[pred_a_col].values
                pred_b = temp[pred_b_col].values

                e_a = actual - pred_a
                e_b = actual - pred_b

                dm_se, dm_se_p = diebold_mariano_test(
                    e1=e_a,
                    e2=e_b,
                    horizon=horizon,
                    power=2
                )

                dm_ae, dm_ae_p = diebold_mariano_test(
                    e1=e_a,
                    e2=e_b,
                    horizon=horizon,
                    power=1
                )

                try:
                    wilcoxon_stat, wilcoxon_p = stats.wilcoxon(
                        np.abs(e_a),
                        np.abs(e_b),
                        zero_method="wilcox",
                        alternative="two-sided"
                    )
                except Exception:
                    wilcoxon_stat, wilcoxon_p = np.nan, np.nan

                rows.append({
                    "asset": asset,
                    "horizon": horizon,
                    "model_a": model_a,
                    "model_b": model_b,
                    "dm_squared_error_stat": round(dm_se, 4) if not np.isnan(dm_se) else np.nan,
                    "dm_squared_error_p_value": round(dm_se_p, 6) if not np.isnan(dm_se_p) else np.nan,
                    "dm_absolute_error_stat": round(dm_ae, 4) if not np.isnan(dm_ae) else np.nan,
                    "dm_absolute_error_p_value": round(dm_ae_p, 6) if not np.isnan(dm_ae_p) else np.nan,
                    "wilcoxon_stat": round(float(wilcoxon_stat), 4) if not np.isnan(wilcoxon_stat) else np.nan,
                    "wilcoxon_p_value": round(float(wilcoxon_p), 6) if not np.isnan(wilcoxon_p) else np.nan,
                    "n": len(temp),
                    "interpretation": "Negative DM means model_a has lower loss than model_b"
                })

    return pd.DataFrame(rows)


stat_tests_df = run_statistical_tests(combined_predictions_df)

display(stat_tests_df)

stat_tests_df.to_csv(
    TESTS_DIR / "statistical_tests_dm_wilcoxon.csv",
    index=False
)

print("Saved:", TESTS_DIR / "statistical_tests_dm_wilcoxon.csv")
print("Exists:", (TESTS_DIR / "statistical_tests_dm_wilcoxon.csv").exists())

,asset,horizon,model_a,model_b,dm_squared_error_stat,dm_squared_error_p_value,dm_absolute_error_stat,dm_absolute_error_p_value,wilcoxon_stat,wilcoxon_p_value,n,interpretation
0,BTC,1,TFT_LOG_RETURN,ARIMA,2.3178,0.020462,2.3956,0.016594,65521.0,0.007356,549,Negative DM means model_a has lower loss than ...
1,BTC,1,TFT_LOG_RETURN,LSTM,-13.2795,0.000000,-22.3172,0.000000,6086.0,0.000000,549,Negative DM means model_a has lower loss than ...
2,BTC,1,LSTM,ARIMA,13.2672,0.000000,22.2626,0.000000,5315.0,0.000000,549,Negative DM means model_a has lower loss than ...
3,BTC,7,TFT_LOG_RETURN,ARIMA,4.4301,0.000009,5.5475,0.000000,31263.0,0.000000,543,Negative DM means model_a has lower loss than ...
4,BTC,7,TFT_LOG_RETURN,LSTM,-4.7736,0.000002,-7.7119,0.000000,15590.0,0.000000,543,Negative DM means model_a has lower loss than ...
5,BTC,7,LSTM,ARIMA,5.2825,0.000000,9.2717,0.000000,7600.0,0.000000,543,Negative DM means model_a has lower loss than ...
6,BTC,30,TFT_LOG_RETURN,ARIMA,2.5356,0.011227,3.3068,0.000944,26257.0,0.000000,520,Negative DM means model_a has lower loss than ...
7,BTC,30,TFT_LOG_RETURN,LSTM,-1.5321,0.125494,-1.6566,0.097596,48191.0,0.000000,520,Negative DM means model_a has lower loss than ...
8,BTC,30,LSTM,ARIMA,2.4644,0.013725,4.1192,0.000038,10533.0,0.000000,520,Negative DM means model_a has lower loss than ...
9,ETH,1,TFT_LOG_RETURN,ARIMA,1.2164,0.223814,1.2101,0.226256,69115.0,0.086573,549,Negative DM means model_a has lower loss than ...
10,ETH,1,TFT_LOG_RETURN,LSTM,-13.8492,0.000000,-18.1648,0.000000,16122.0,0.000000,549,Negative DM means model_a has lower loss than ...
11,ETH,1,LSTM,ARIMA,13.9158,0.000000,18.4203,0.000000,15517.0,0.000000,549,Negative DM means model_a has lower loss than ...
12,ETH,7,TFT_LOG_RETURN,ARIMA,3.3752,0.000738,4.3255,0.000015,40095.0,0.000000,543,Negative DM means model_a has lower loss than ...
13,ETH,7,TFT_LOG_RETURN,LSTM,-5.7364,0.000000,-6.4792,0.000000,24132.0,0.000000,543,Negative DM means model_a has lower loss than ...
14,ETH,7,LSTM,ARIMA,6.5707,0.000000,8.3416,0.000000,12811.0,0.000000,543,Negative DM means model_a has lower loss than ...
15,ETH,30,TFT_LOG_RETURN,ARIMA,2.9753,0.002927,3.2883,0.001008,28835.0,0.000000,520,Negative DM means model_a has lower loss than ...
16,ETH,30,TFT_LOG_RETURN,LSTM,-0.3849,0.700306,-0.3643,0.715654,63142.0,0.180769,520,Negative DM means model_a has lower loss than ...
17,ETH,30,LSTM,ARIMA,2.4312,0.015048,2.4508,0.014254,38402.0,0.000000,520,Negative DM means model_a has lower loss than ...
18,BNB,1,TFT_LOG_RETURN,ARIMA,-0.1137,0.909496,0.4080,0.683258,70960.0,0.223383,549,Negative DM means model_a has lower loss than ...
19,BNB,1,TFT_LOG_RETURN,LSTM,-11.8805,0.000000,-18.2847,0.000000,18975.0,0.000000,549,Negative DM means model_a has lower loss than ...
20,BNB,1,LSTM,ARIMA,12.4376,0.000000,19.0608,0.000000,17389.0,0.000000,549,Negative DM means model_a has lower loss than ...
21,BNB,7,TFT_LOG_RETURN,ARIMA,2.8113,0.004934,3.3878,0.000704,49609.0,0.000000,543,Negative DM means model_a has lower loss than ...
22,BNB,7,TFT_LOG_RETURN,LSTM,-3.0016,0.002686,-5.2989,0.000000,30185.0,0.000000,543,Negative DM means model_a has lower loss than ...
23,BNB,7,LSTM,ARIMA,6.0105,0.000000,8.1614,0.000000,17710.0,0.000000,543,Negative DM means model_a has lower loss than ...
24,BNB,30,TFT_LOG_RETURN,ARIMA,2.1896,0.028551,2.9108,0.003605,23752.0,0.000000,520,Negative DM means model_a has lower loss than ...
25,BNB,30,TFT_LOG_RETURN,LSTM,3.0334,0.002418,3.3510,0.000805,24429.0,0.000000,520,Negative DM means model_a has lower loss than ...
26,BNB,30,LSTM,ARIMA,-0.7183,0.472594,0.5176,0.604769,53073.0,0.000019,520,Negative DM means model_a has lower loss than ...

Saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/05_Statistical_Tests/statistical_tests_dm_wilcoxon.csv
Exists: True

In [44]:
# ============================================================
# Clean statistical interpretation summary
# ============================================================

def interpret_dm(row):
    p = row["dm_squared_error_p_value"]
    dm = row["dm_squared_error_stat"]
    model_a = row["model_a"]
    model_b = row["model_b"]

    if pd.isna(p):
        return "No conclusion"

    if p >= 0.05:
        return f"No statistically significant difference between {model_a} and {model_b}"

    if dm < 0:
        return f"{model_a} significantly outperforms {model_b}"

    if dm > 0:
        return f"{model_b} significantly outperforms {model_a}"

    return "No conclusion"


stat_summary_df = stat_tests_df.copy()
stat_summary_df["conclusion_squared_error"] = stat_summary_df.apply(interpret_dm, axis=1)

stat_summary_clean_df = stat_summary_df[
    [
        "asset",
        "horizon",
        "model_a",
        "model_b",
        "dm_squared_error_stat",
        "dm_squared_error_p_value",
        "wilcoxon_p_value",
        "n",
        "conclusion_squared_error"
    ]
].copy()

display(stat_summary_clean_df)

stat_summary_clean_df.to_csv(
    TESTS_DIR / "statistical_tests_clean_summary.csv",
    index=False
)

print("Saved:", TESTS_DIR / "statistical_tests_clean_summary.csv")
print("Exists:", (TESTS_DIR / "statistical_tests_clean_summary.csv").exists())

,asset,horizon,model_a,model_b,dm_squared_error_stat,dm_squared_error_p_value,wilcoxon_p_value,n,conclusion_squared_error
0,BTC,1,TFT_LOG_RETURN,ARIMA,2.3178,0.020462,0.007356,549,ARIMA significantly outperforms TFT_LOG_RETURN
1,BTC,1,TFT_LOG_RETURN,LSTM,-13.2795,0.000000,0.000000,549,TFT_LOG_RETURN significantly outperforms LSTM
2,BTC,1,LSTM,ARIMA,13.2672,0.000000,0.000000,549,ARIMA significantly outperforms LSTM
3,BTC,7,TFT_LOG_RETURN,ARIMA,4.4301,0.000009,0.000000,543,ARIMA significantly outperforms TFT_LOG_RETURN
4,BTC,7,TFT_LOG_RETURN,LSTM,-4.7736,0.000002,0.000000,543,TFT_LOG_RETURN significantly outperforms LSTM
5,BTC,7,LSTM,ARIMA,5.2825,0.000000,0.000000,543,ARIMA significantly outperforms LSTM
6,BTC,30,TFT_LOG_RETURN,ARIMA,2.5356,0.011227,0.000000,520,ARIMA significantly outperforms TFT_LOG_RETURN
7,BTC,30,TFT_LOG_RETURN,LSTM,-1.5321,0.125494,0.000000,520,No statistically significant difference betwee...
8,BTC,30,LSTM,ARIMA,2.4644,0.013725,0.000000,520,ARIMA significantly outperforms LSTM
9,ETH,1,TFT_LOG_RETURN,ARIMA,1.2164,0.223814,0.086573,549,No statistically significant difference betwee...
10,ETH,1,TFT_LOG_RETURN,LSTM,-13.8492,0.000000,0.000000,549,TFT_LOG_RETURN significantly outperforms LSTM
11,ETH,1,LSTM,ARIMA,13.9158,0.000000,0.000000,549,ARIMA significantly outperforms LSTM
12,ETH,7,TFT_LOG_RETURN,ARIMA,3.3752,0.000738,0.000000,543,ARIMA significantly outperforms TFT_LOG_RETURN
13,ETH,7,TFT_LOG_RETURN,LSTM,-5.7364,0.000000,0.000000,543,TFT_LOG_RETURN significantly outperforms LSTM
14,ETH,7,LSTM,ARIMA,6.5707,0.000000,0.000000,543,ARIMA significantly outperforms LSTM
15,ETH,30,TFT_LOG_RETURN,ARIMA,2.9753,0.002927,0.000000,520,ARIMA significantly outperforms TFT_LOG_RETURN
16,ETH,30,TFT_LOG_RETURN,LSTM,-0.3849,0.700306,0.180769,520,No statistically significant difference betwee...
17,ETH,30,LSTM,ARIMA,2.4312,0.015048,0.000000,520,ARIMA significantly outperforms LSTM
18,BNB,1,TFT_LOG_RETURN,ARIMA,-0.1137,0.909496,0.223383,549,No statistically significant difference betwee...
19,BNB,1,TFT_LOG_RETURN,LSTM,-11.8805,0.000000,0.000000,549,TFT_LOG_RETURN significantly outperforms LSTM
20,BNB,1,LSTM,ARIMA,12.4376,0.000000,0.000000,549,ARIMA significantly outperforms LSTM
21,BNB,7,TFT_LOG_RETURN,ARIMA,2.8113,0.004934,0.000000,543,ARIMA significantly outperforms TFT_LOG_RETURN
22,BNB,7,TFT_LOG_RETURN,LSTM,-3.0016,0.002686,0.000000,543,TFT_LOG_RETURN significantly outperforms LSTM
23,BNB,7,LSTM,ARIMA,6.0105,0.000000,0.000000,543,ARIMA significantly outperforms LSTM
24,BNB,30,TFT_LOG_RETURN,ARIMA,2.1896,0.028551,0.000000,520,ARIMA significantly outperforms TFT_LOG_RETURN
25,BNB,30,TFT_LOG_RETURN,LSTM,3.0334,0.002418,0.000000,520,LSTM significantly outperforms TFT_LOG_RETURN
26,BNB,30,LSTM,ARIMA,-0.7183,0.472594,0.000019,520,No statistically significant difference betwee...

Saved: /content/drive/MyDrive/Revi_Diploma_Reproducibility_Package/05_Statistical_Tests/statistical_tests_clean_summary.csv
Exists: True

In [45]:
final_files = [
    RESULTS_DIR / "final_metrics_arima_lstm_tft.csv",
    RESULTS_DIR / "combined_predictions_arima_lstm_tft.csv",
    TESTS_DIR / "statistical_tests_dm_wilcoxon.csv",
    TESTS_DIR / "statistical_tests_clean_summary.csv",
]

for f in final_files:
    print(f.name, "OK" if f.exists() else "MISSING")

final_metrics_arima_lstm_tft.csv OK
combined_predictions_arima_lstm_tft.csv OK
statistical_tests_dm_wilcoxon.csv OK
statistical_tests_clean_summary.csv OK

In [1]:
from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import shutil

BASE_DIR = Path("/content/drive/MyDrive/Revi_Diploma_Reproducibility_Package")
ZIP_PATH = "/content/Revi_Diploma_Reproducibility_Package_FINAL"

shutil.make_archive(ZIP_PATH, 'zip', BASE_DIR)

print("ZIP u krijua me sukses:")
print(ZIP_PATH + ".zip")

Mounted at /content/drive
ZIP u krijua me sukses:
/content/Revi_Diploma_Reproducibility_Package_FINAL.zip

In [2]:
from google.colab import files
files.download("/content/Revi_Diploma_Reproducibility_Package_FINAL.zip")